# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dialog_about(object):
    def setupUi(self, dialog_about):
        dialog_about.setObjectName("dialog_about")
        dialog_about.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        dialog_about.resize(640, 420)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dialog_about.sizePolicy().hasHeightForWidth())
        dialog_about.setSizePolicy(sizePolicy)
        dialog_about.setMinimumSize(QtCore.QSize(640, 420))
        dialog_about.setMaximumSize(QtCore.QSize(640, 420))
        dialog_about.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Spanish, QtCore.QLocale.Country.Venezuela))
        self.label_logo = QtWidgets.QLabel(parent=dialog_about)
        self.label_logo.setGeometry(QtCore.QRect(20, 0, 140, 140))
        self.label_logo.setText("")
        self.label_logo.setPixmap(QtGui.QPixmap("images/concrete-mixer.png"))
        self.label_logo.setScaledContents(True)
        self.label_logo.setObjectName("label_logo")
        self.label_about = QtWidgets.QLabel(parent=dialog_about)
        self.label_about.setGeometry(QtCore.QRect(180, 10, 440, 391))
        self.label_about.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_about.setWordWrap(True)
        self.label_about.setObjectName("label_about")

        self.retranslateUi(dialog_about)
        QtCore.QMetaObject.connectSlotsByName(dialog_about)

    def retranslateUi(self, dialog_about):
        _translate = QtCore.QCoreApplication.translate
        dialog_about.setWindowTitle(_translate("dialog_about", "Info"))
        self.label_about.setText(_translate("dialog_about", "<html><head/><body><p><span style=\" font-size:12pt;\">Acerca de </span><span style=\" font-size:12pt; font-weight:700;\">Concretus</span></p><p>Versión: 1.0.0 </p><p>Fecha: 2025-02-20 </p><p>Copyright © 2025 Jesús Rivas </p><p><span style=\" font-weight:700; font-style:italic;\">Concretus</span> es un software especializado en el diseño y dosificación de mezclas de concreto. Actualmente incorpora tres métodos:</p><p><span style=\" font-weight:700;\">Método MCE</span>: Basado en el libro <span style=\" font-style:italic;\">Manual del Concreto Estructural</span> de Porrero, Ramos, Grases y Velazco (2009)</p><p><span style=\" font-weight:700;\">Método ACI</span>: Basado en el manual <span style=\" font-style:italic;\">ACI PRC-211.1-22 - Selecting Proportions for Normal-Density and High-Density Concrete – Guide </span>del Comité 211 del Instituto Americano del Concreto (2022)</p><p><span style=\" font-weight:700;\">Método DoE</span>: Basado en el libro <span style=\" font-style:italic;\">Design of Normal Concrete Mixes</span> de Teychenné, Franklin y Erntroy (1997)</p><p>Desarrollado por: Jesús Alejandro Rivas Simancas</p><p>Correo electrónico: rivas601@gmail.com </p><p>Licencia: General Public License (GPL) </p></body></html>"))
