# Form implementation generated from reading ui file 'conversion_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ConversionDialog(object):
    def setupUi(self, ConversionDialog):
        ConversionDialog.setObjectName("ConversionDialog")
        ConversionDialog.resize(360, 230)
        ConversionDialog.setMinimumSize(QtCore.QSize(360, 230))
        ConversionDialog.setMaximumSize(QtCore.QSize(360, 230))
        ConversionDialog.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Spanish, QtCore.QLocale.Country.Venezuela))
        ConversionDialog.setSizeGripEnabled(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(ConversionDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_dosage_type = QtWidgets.QGroupBox(parent=ConversionDialog)
        self.groupBox_dosage_type.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Spanish, QtCore.QLocale.Country.Venezuela))
        self.groupBox_dosage_type.setObjectName("groupBox_dosage_type")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_dosage_type)
        self.formLayout.setObjectName("formLayout")
        self.radioButton_1 = QtWidgets.QRadioButton(parent=self.groupBox_dosage_type)
        self.radioButton_1.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Spanish, QtCore.QLocale.Country.Venezuela))
        self.radioButton_1.setChecked(True)
        self.radioButton_1.setObjectName("radioButton_1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.radioButton_1)
        self.radioButton_2 = QtWidgets.QRadioButton(parent=self.groupBox_dosage_type)
        self.radioButton_2.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Spanish, QtCore.QLocale.Country.Venezuela))
        self.radioButton_2.setObjectName("radioButton_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.radioButton_2)
        self.verticalLayout.addWidget(self.groupBox_dosage_type)
        self.formLayout_dosage_data = QtWidgets.QFormLayout()
        self.formLayout_dosage_data.setObjectName("formLayout_dosage_data")
        self.label_dosage = QtWidgets.QLabel(parent=ConversionDialog)
        self.label_dosage.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Spanish, QtCore.QLocale.Country.Venezuela))
        self.label_dosage.setObjectName("label_dosage")
        self.formLayout_dosage_data.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_dosage)
        self.doubleSpinBox_dosage = QtWidgets.QDoubleSpinBox(parent=ConversionDialog)
        self.doubleSpinBox_dosage.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Spanish, QtCore.QLocale.Country.Venezuela))
        self.doubleSpinBox_dosage.setObjectName("doubleSpinBox_dosage")
        self.formLayout_dosage_data.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.doubleSpinBox_dosage)
        self.label_dosage_relative_density = QtWidgets.QLabel(parent=ConversionDialog)
        self.label_dosage_relative_density.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Spanish, QtCore.QLocale.Country.Venezuela))
        self.label_dosage_relative_density.setObjectName("label_dosage_relative_density")
        self.formLayout_dosage_data.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_dosage_relative_density)
        self.doubleSpinBox_dosage_relative_density = QtWidgets.QDoubleSpinBox(parent=ConversionDialog)
        self.doubleSpinBox_dosage_relative_density.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Spanish, QtCore.QLocale.Country.Venezuela))
        self.doubleSpinBox_dosage_relative_density.setDecimals(3)
        self.doubleSpinBox_dosage_relative_density.setObjectName("doubleSpinBox_dosage_relative_density")
        self.formLayout_dosage_data.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.doubleSpinBox_dosage_relative_density)
        self.label_bag_weight = QtWidgets.QLabel(parent=ConversionDialog)
        self.label_bag_weight.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Spanish, QtCore.QLocale.Country.Venezuela))
        self.label_bag_weight.setObjectName("label_bag_weight")
        self.formLayout_dosage_data.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_bag_weight)
        self.doubleSpinBox_bag_weight = QtWidgets.QDoubleSpinBox(parent=ConversionDialog)
        self.doubleSpinBox_bag_weight.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Spanish, QtCore.QLocale.Country.Venezuela))
        self.doubleSpinBox_bag_weight.setObjectName("doubleSpinBox_bag_weight")
        self.formLayout_dosage_data.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.doubleSpinBox_bag_weight)
        self.verticalLayout.addLayout(self.formLayout_dosage_data)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_convert = QtWidgets.QPushButton(parent=ConversionDialog)
        self.pushButton_convert.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Spanish, QtCore.QLocale.Country.Venezuela))
        self.pushButton_convert.setObjectName("pushButton_convert")
        self.horizontalLayout.addWidget(self.pushButton_convert)
        self.pushButton_cancel = QtWidgets.QPushButton(parent=ConversionDialog)
        self.pushButton_cancel.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Spanish, QtCore.QLocale.Country.Venezuela))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout.addWidget(self.pushButton_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_dosage.setBuddy(self.doubleSpinBox_dosage)
        self.label_dosage_relative_density.setBuddy(self.doubleSpinBox_dosage_relative_density)
        self.label_bag_weight.setBuddy(self.doubleSpinBox_bag_weight)

        self.retranslateUi(ConversionDialog)
        self.radioButton_2.toggled['bool'].connect(self.doubleSpinBox_bag_weight.setDisabled) # type: ignore
        self.radioButton_2.toggled['bool'].connect(self.label_bag_weight.setDisabled) # type: ignore
        self.pushButton_convert.clicked.connect(ConversionDialog.accept) # type: ignore
        self.pushButton_cancel.clicked.connect(ConversionDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ConversionDialog)
        ConversionDialog.setTabOrder(self.radioButton_1, self.radioButton_2)
        ConversionDialog.setTabOrder(self.radioButton_2, self.doubleSpinBox_dosage)
        ConversionDialog.setTabOrder(self.doubleSpinBox_dosage, self.doubleSpinBox_dosage_relative_density)
        ConversionDialog.setTabOrder(self.doubleSpinBox_dosage_relative_density, self.doubleSpinBox_bag_weight)
        ConversionDialog.setTabOrder(self.doubleSpinBox_bag_weight, self.pushButton_convert)
        ConversionDialog.setTabOrder(self.pushButton_convert, self.pushButton_cancel)

    def retranslateUi(self, ConversionDialog):
        _translate = QtCore.QCoreApplication.translate
        ConversionDialog.setWindowTitle(_translate("ConversionDialog", "Conversión"))
        self.groupBox_dosage_type.setTitle(_translate("ConversionDialog", "Dosificación del aditivo"))
        self.radioButton_1.setText(_translate("ConversionDialog", "ml (o cm³) / saco de cemento (o material cementante)"))
        self.radioButton_2.setText(_translate("ConversionDialog", "ml (o cm³) / kg de cemento (o material cementante)"))
        self.label_dosage.setText(_translate("ConversionDialog", "Dosis (ml o cm³)"))
        self.label_dosage_relative_density.setText(_translate("ConversionDialog", "Densidad relativa"))
        self.label_bag_weight.setText(_translate("ConversionDialog", "Peso del saco (kgf)"))
        self.pushButton_convert.setText(_translate("ConversionDialog", "Convetir"))
        self.pushButton_cancel.setText(_translate("ConversionDialog", "Cancelar"))
