# Form implementation generated from reading ui file 'config_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ConfigDialog(object):
    def setupUi(self, ConfigDialog):
        ConfigDialog.setObjectName("ConfigDialog")
        ConfigDialog.resize(300, 144)
        ConfigDialog.setMaximumSize(QtCore.QSize(300, 144))
        ConfigDialog.setAutoFillBackground(False)
        ConfigDialog.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Spanish, QtCore.QLocale.Country.Venezuela))
        self.verticalLayout = QtWidgets.QVBoxLayout(ConfigDialog)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 9)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_lang = QtWidgets.QLabel(parent=ConfigDialog)
        self.label_lang.setObjectName("label_lang")
        self.verticalLayout.addWidget(self.label_lang)
        self.comboBox_lang = QtWidgets.QComboBox(parent=ConfigDialog)
        self.comboBox_lang.setObjectName("comboBox_lang")
        self.verticalLayout.addWidget(self.comboBox_lang)
        self.label_units = QtWidgets.QLabel(parent=ConfigDialog)
        self.label_units.setObjectName("label_units")
        self.verticalLayout.addWidget(self.label_units)
        self.comboBox_units = QtWidgets.QComboBox(parent=ConfigDialog)
        self.comboBox_units.setObjectName("comboBox_units")
        self.verticalLayout.addWidget(self.comboBox_units)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_accept = QtWidgets.QPushButton(parent=ConfigDialog)
        self.pushButton_accept.setObjectName("pushButton_accept")
        self.horizontalLayout.addWidget(self.pushButton_accept)
        self.pushButton_cancel = QtWidgets.QPushButton(parent=ConfigDialog)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout.addWidget(self.pushButton_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_lang.setBuddy(self.comboBox_lang)
        self.label_units.setBuddy(self.comboBox_units)

        self.retranslateUi(ConfigDialog)
        self.pushButton_accept.clicked.connect(ConfigDialog.accept) # type: ignore
        self.pushButton_cancel.clicked.connect(ConfigDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ConfigDialog)

    def retranslateUi(self, ConfigDialog):
        _translate = QtCore.QCoreApplication.translate
        ConfigDialog.setWindowTitle(_translate("ConfigDialog", "Configuración"))
        self.label_lang.setText(_translate("ConfigDialog", "Idioma:"))
        self.label_units.setText(_translate("ConfigDialog", "Unidades:"))
        self.pushButton_accept.setText(_translate("ConfigDialog", "Aceptar"))
        self.pushButton_cancel.setText(_translate("ConfigDialog", "Cancelar"))
