# Form implementation generated from reading ui file 'report_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ReportDialog(object):
    def setupUi(self, ReportDialog):
        ReportDialog.setObjectName("ReportDialog")
        ReportDialog.resize(400, 165)
        ReportDialog.setMinimumSize(QtCore.QSize(400, 165))
        ReportDialog.setMaximumSize(QtCore.QSize(400, 165))
        ReportDialog.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Spanish, QtCore.QLocale.Country.Venezuela))
        self.verticalLayout = QtWidgets.QVBoxLayout(ReportDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_report = QtWidgets.QGroupBox(parent=ReportDialog)
        self.groupBox_report.setObjectName("groupBox_report")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_report)
        self.formLayout.setObjectName("formLayout")
        self.radioButton_basic_report = QtWidgets.QRadioButton(parent=self.groupBox_report)
        self.radioButton_basic_report.setChecked(True)
        self.radioButton_basic_report.setObjectName("radioButton_basic_report")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.radioButton_basic_report)
        self.radioButton_full_report = QtWidgets.QRadioButton(parent=self.groupBox_report)
        self.radioButton_full_report.setObjectName("radioButton_full_report")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.radioButton_full_report)
        self.verticalLayout.addWidget(self.groupBox_report)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_decimals = QtWidgets.QLabel(parent=ReportDialog)
        self.label_decimals.setObjectName("label_decimals")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_decimals)
        self.spinBox_decimals = QtWidgets.QSpinBox(parent=ReportDialog)
        self.spinBox_decimals.setMaximum(10)
        self.spinBox_decimals.setProperty("value", 2)
        self.spinBox_decimals.setObjectName("spinBox_decimals")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.spinBox_decimals)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_accept = QtWidgets.QPushButton(parent=ReportDialog)
        self.pushButton_accept.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.pushButton_accept.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Spanish, QtCore.QLocale.Country.Venezuela))
        self.pushButton_accept.setObjectName("pushButton_accept")
        self.horizontalLayout.addWidget(self.pushButton_accept)
        self.pushButton_cancel = QtWidgets.QPushButton(parent=ReportDialog)
        self.pushButton_cancel.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.pushButton_cancel.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Spanish, QtCore.QLocale.Country.Venezuela))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout.addWidget(self.pushButton_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_decimals.setBuddy(self.spinBox_decimals)

        self.retranslateUi(ReportDialog)
        self.pushButton_accept.clicked.connect(ReportDialog.accept) # type: ignore
        self.pushButton_cancel.clicked.connect(ReportDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ReportDialog)
        ReportDialog.setTabOrder(self.radioButton_basic_report, self.radioButton_full_report)
        ReportDialog.setTabOrder(self.radioButton_full_report, self.spinBox_decimals)
        ReportDialog.setTabOrder(self.spinBox_decimals, self.pushButton_accept)
        ReportDialog.setTabOrder(self.pushButton_accept, self.pushButton_cancel)

    def retranslateUi(self, ReportDialog):
        _translate = QtCore.QCoreApplication.translate
        ReportDialog.setWindowTitle(_translate("ReportDialog", "Reportes"))
        self.groupBox_report.setTitle(_translate("ReportDialog", "Tipo de reporte"))
        self.radioButton_basic_report.setToolTip(_translate("ReportDialog", "<html><head/><body><p>Incluye los datos ingresados y resultados.</p></body></html>"))
        self.radioButton_basic_report.setText(_translate("ReportDialog", "Reporte básico / Resumen del diseño"))
        self.radioButton_full_report.setToolTip(_translate("ReportDialog", "<html><head/><body><p>Incluye los datos ingresados, cálculos realizados y resultados.</p></body></html>"))
        self.radioButton_full_report.setText(_translate("ReportDialog", "Reporte completo / Resumen del diseño y cálculos realizados"))
        self.label_decimals.setText(_translate("ReportDialog", "Precisión decimal del reporte"))
        self.pushButton_accept.setText(_translate("ReportDialog", "Aceptar"))
        self.pushButton_cancel.setText(_translate("ReportDialog", "Cancelar"))
