# Form implementation generated from reading ui file 'trial_mix_widget.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TrialMixWidget(object):
    def setupUi(self, TrialMixWidget):
        TrialMixWidget.setObjectName("TrialMixWidget")
        TrialMixWidget.resize(655, 475)
        TrialMixWidget.setMinimumSize(QtCore.QSize(655, 475))
        TrialMixWidget.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Spanish, QtCore.QLocale.Country.Venezuela))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(TrialMixWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(parent=TrialMixWidget)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(parent=TrialMixWidget)
        self.doubleSpinBox.setDecimals(6)
        self.doubleSpinBox.setMaximum(100.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.doubleSpinBox)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.radioButton = QtWidgets.QRadioButton(parent=TrialMixWidget)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(parent=TrialMixWidget)
        self.label_2.setEnabled(False)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.spinBox = QtWidgets.QSpinBox(parent=TrialMixWidget)
        self.spinBox.setEnabled(False)
        self.spinBox.setMaximum(100)
        self.spinBox.setObjectName("spinBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.spinBox)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tableWidget = QtWidgets.QTableWidget(parent=TrialMixWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_2.addWidget(self.tableWidget)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.label.setBuddy(self.doubleSpinBox)
        self.label_2.setBuddy(self.spinBox)

        self.retranslateUi(TrialMixWidget)
        self.radioButton.toggled['bool'].connect(self.label_2.setEnabled) # type: ignore
        self.radioButton.toggled['bool'].connect(self.spinBox.setEnabled) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(TrialMixWidget)

    def retranslateUi(self, TrialMixWidget):
        _translate = QtCore.QCoreApplication.translate
        TrialMixWidget.setWindowTitle(_translate("TrialMixWidget", "Form"))
        self.label.setText(_translate("TrialMixWidget", "Volumen para la prueba (m³)"))
        self.radioButton.setText(_translate("TrialMixWidget", "Consider desperdicio"))
        self.label_2.setText(_translate("TrialMixWidget", "Desperdicio (%)"))
        self.tableWidget.setSortingEnabled(False)
