# Form implementation generated from reading ui file 'welcome_widget.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WelcomeWidget(object):
    def setupUi(self, WelcomeWidget):
        WelcomeWidget.setObjectName("WelcomeWidget")
        WelcomeWidget.resize(790, 530)
        WelcomeWidget.setMinimumSize(QtCore.QSize(790, 530))
        WelcomeWidget.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Spanish, QtCore.QLocale.Country.Venezuela))
        self.verticalLayout = QtWidgets.QVBoxLayout(WelcomeWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_welcome = QtWidgets.QLabel(parent=WelcomeWidget)
        self.label_welcome.setObjectName("label_welcome")
        self.verticalLayout.addWidget(self.label_welcome)
        self.widget = QtWidgets.QWidget(parent=WelcomeWidget)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_logo = QtWidgets.QLabel(parent=self.widget)
        self.label_logo.setMaximumSize(QtCore.QSize(250, 250))
        self.label_logo.setText("")
        self.label_logo.setPixmap(QtGui.QPixmap("../../assets/images/about_logo.png"))
        self.label_logo.setScaledContents(True)
        self.label_logo.setObjectName("label_logo")
        self.gridLayout_2.addWidget(self.label_logo, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_powerd_by = QtWidgets.QLabel(parent=WelcomeWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_powerd_by.sizePolicy().hasHeightForWidth())
        self.label_powerd_by.setSizePolicy(sizePolicy)
        self.label_powerd_by.setMinimumSize(QtCore.QSize(221, 0))
        self.label_powerd_by.setWordWrap(True)
        self.label_powerd_by.setObjectName("label_powerd_by")
        self.horizontalLayout.addWidget(self.label_powerd_by)
        self.label_pyqt_logo = QtWidgets.QLabel(parent=WelcomeWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_pyqt_logo.sizePolicy().hasHeightForWidth())
        self.label_pyqt_logo.setSizePolicy(sizePolicy)
        self.label_pyqt_logo.setMinimumSize(QtCore.QSize(60, 63))
        self.label_pyqt_logo.setMaximumSize(QtCore.QSize(60, 63))
        self.label_pyqt_logo.setText("")
        self.label_pyqt_logo.setPixmap(QtGui.QPixmap("../../assets/images/pyqt_logo.png"))
        self.label_pyqt_logo.setScaledContents(True)
        self.label_pyqt_logo.setObjectName("label_pyqt_logo")
        self.horizontalLayout.addWidget(self.label_pyqt_logo)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(1, 1)

        self.retranslateUi(WelcomeWidget)
        QtCore.QMetaObject.connectSlotsByName(WelcomeWidget)

    def retranslateUi(self, WelcomeWidget):
        _translate = QtCore.QCoreApplication.translate
        WelcomeWidget.setWindowTitle(_translate("WelcomeWidget", "Form"))
        self.label_welcome.setText(_translate("WelcomeWidget", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt;\">Bienvenido a </span><span style=\" font-size:24pt; font-weight:700;\">Concretus</span></p><p align=\"center\"><span style=\" font-size:16pt; font-style:italic;\">Diseño y dosificación de mezclas de concreto</span></p></body></html>"))
        self.label_powerd_by.setText(_translate("WelcomeWidget", "<html><head/><body><p><span style=\" font-size:12pt;\">Desarrollo de interfaz gráfica de usuario en Python con PyQt6</span></p></body></html>"))
